---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
    force: true

driver:
  name: docker

platforms:
  - name: instance
    image: rockylinux:8
    command: ""
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  playbooks:
    converge: ../resources/converge.yml
  env:
    ANSIBLE_VERBOSITY: "1"
verifier:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: "1"

lint: |
  set -e
  yamllint .
  ansible-lint .
