---
- name: Converge
  hosts: instance
  become: true
  gather_facts: true

  pre_tasks:
    - name: Print ansible_user
      ansible.builtin.debug:
        var: ansible_user

    - name: Wait for systemd to complete initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - mirsg.template
