name: mirsg.role_name
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        molecule_scenario:
          - centos7
          - rocky8

    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install rsync
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible ansible-lint molecule molecule-plugins[docker] docker requests==2.29.0

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          molecule --debug test -s ${{ matrix.molecule_scenario }}
